version: '3.8'

services:
  ollama:
    image: ollama/ollama:0.6.3
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
